# workflow file for building a PDF document using GitHub Actions

name: Build Typst PDF


on:
 
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v4


      - name: Compile all .typ to PDF
        run: |
          mkdir -p output
          mkdir -p output/assets
          cp assets/pdf-icon.png output/assets/
          cp assets/title.png output/assets/
          for file in ./docs/*.typ; do
            filename=$(basename "$file" .typ)
            if [[ "$filename" != Diario* && "$filename" != Tesi*]]; then
              typst compile "$file" output/"$filename.pdf"
            fi
          done
        
      - name: Create simple HTML index
        run: |
          echo "<!DOCTYPE html>
                <html>
                <head>
                    <meta charset="UTF-8">
                
                    <link rel="stylesheet" href="CSS/style.css" media="screen"/>
                    <title>Documentazione</title>
                    <link rel="icon" href="assets/title.png" type="image/png">
                    <style>
                        * {
                        margin: 0;
                        padding: 0;
                        box-sizing: border-box;
                        }
                
                        body {
                        background-color: var(--main-bg-color);
                        font-family: "Arial";
                        display: flex;
                        justify-content: center;
                        flex-direction: column;
                        align-items: center;
                        height: 100%;
                        line-height: 1.5em
                        }

                                   
                        /*Variabili colori*/
                        :root {
                        --main-bg-color: #2a2a2a;
                        --list-bg-color: #3a1f1f;
                        --text-color: #1f1f1f;
                        --link-color: #fcb52f;
                        --text-color-light: #fff4f6
                        }
                
                        /* Wrapper */
                        .wrapper {
                        margin-top: 0.5em;
                        margin-bottom: 0.5em;
                        background-color: var(--main-bg-color);
                        width: 100%;
                        max-width: 1200px;
                        height: fit-content;
                        padding: 0.5em;
                        }
                
                        .link {
                        color: var(--link-color);
                        }
                
                        /* Titolo h1 */
                        h1 {
                            font-size: 3.5em;
                            text-align: center;
                            margin: 0.5em;
                            color: var(--text-color-light);
                            line-height: 1.2em;
                        }

                        .content h2 {
                            font-size: 2.5em;
                            text-align: center;
                            margin: 0.5em;
                            color: var(--text-color-light);
                            line-height: 1.2em;
                        }
                
                        .content p {
                        font-size: 1.2em;
                        line-height: 1.5em;
                        color: var(--text-color-light);
                        text-align: center;
                        }
                
                        .content-link {
                        margin-top: 1em;
                        }

                        .lista-doc{
                          max-width: 70%;
                          margin: 0 auto;
                        }

                        .document-list {
                         list-style: none;
                         padding: 0;
                         width: 100%;
                         margin-left: 2em;
                         margin-right: 2em;
                         font-family: "Segoe UI", sans-serif;
                         color: var(--text-color-light);
                       }
                       
                       .document-list li {
                         background-color: var(--list-bg-color);
                          border: 1px solid #ddd;
                          margin-bottom: 0.4rem;
                          padding: 1rem 1.5rem;
                          border-radius: 6px;
                          transition: background-color 0.2s ease, box-shadow 0.2s ease;
                          display: flex;
                          align-items: flex-start; /* cambia da center a flex-start */
                          justify-content: space-between;
                          box-shadow: 0 2px 4px rgba(0,0,0,0.05);
                          white-space: normal; /* assicura che il testo vada a capo */
                          word-break: break-word; /* evita overflow di parole lunghe */
                       }
                       
                       .document-list li:hover {
                         background-color: #574242;
                         box-shadow: 0 4px 8px rgba(0,0,0,0.1);
                       }
                       
                       .document-list li a {
                         color: var(--text-color-light);
                         text-decoration: none;
                         font-weight: 500;
                         flex-grow: 1;
                       }
                       
                       .document-list li a:hover {
                         text-decoration: underline;
                       }

                       .icon {
                         width: 25px;
                         object-fit: contain;
                         margin-right: 0.5rem;
                         vertical-align: middle;
                       }

                        @media (max-width: 600px) {
                            .document-list {
                              margin-left: 0em;
                              margin-right: 0em;
                            }
                            .document-list li {
                              margin-bottom: 0.8rem;
                            }

                            .lista-doc{
                              max-width: 100%;
                            }

                            .document-list li a {
                              font-size: 2em;
                            }
                            
                        }

                        /* Tablet: da 601px a 1024px */
                        @media (min-width: 601px) and (max-width: 1024px) {
                            .document-list {
                              margin-left: 0em;
                              margin-right: 0em;
                            }
                            .lista-doc{
                              max-width: 100%;
                            }
                            .document-list li a {
                              font-size: 2em;
                            }
                        }   
                    </style>
                </head>
                <body>
                    <div class="wrapper">
                    <main id="main-content">
                        
                        <!-- Intestazione -->
                        <section class="content">
                            <h1>Stage Bitdefender</h1>
                            <p>
                                Sito della documentazione del progetto di stage "Gestione della Sicurezza Aziendale: Caso studio con Bitdefender".
                            </p>
                        </section>
                
                        <!-- Documentyi -->
                        <section class="content">
                            <h2>Documenti</h2>
                            <div class="lista-doc">
                                <ul class="document-list">" > output/index.html
          for file in output/*.pdf; do
            filename=$(basename "$file")
            echo "<li><img src="assets/pdf-icon.png" class="icon" /><a href=\"$filename\" target=\"_blank\">$filename</a></li>" >> output/index.html
          done
          echo "</ul><h2>Proposta di Stage</h2><ul class="document-list">" >> output/index.html
          for file in ./docs/*.pdf; do
            cp "$file" output/
            filename=$(basename "$file")
            echo "<li><img src="assets/pdf-icon.png" class="icon" /><a href=\"$filename\" target=\"_blank\">$filename</a></li>" >> output/index.html
          done
          echo "</ul></div></section></main></div></body></html>" >> output/index.html
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
          keep_files: false
          commit_message: "Deploy PDF documents"

